name: CI
on: [push, pull_request]

jobs:
    php_cs_fixer:
        name: PHP-CS-Fxier
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php_version:
                    - 8.0
                    - 8.1
                perfer:
                    - stable
        steps:
            - uses: actions/checkout@master
            - name: Install Dependencies
              run: composer install --prefer-dist --no-interaction --no-suggest

    phpunit:
        name: phpunit
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php_version:
                    - 8.0
                    - 8.1
                perfer:
                    - stable
        steps:
            - uses: actions/checkout@master
            - name: Install Dependencies
              run: composer install --prefer-dist --no-interaction --no-suggest
            - name: Run PHPUnit
              run: ./vendor/bin/phpunit
